### ISSUE TITLE
docs(common): fix typo in `HttpClient` docs (HTTPResponse --> HttpResponse)

### ISSUE THREAD

**Issue by gkalpak** [angularathens/2nd-workshop-angular-contrib#26]
The `HttpClient` [API docs][1] ([source code][2]) contain several occurrences (currently 68) of `HTTPResponse` (with uppercase `HTTP`). The actual class, however, is called `HttpResponse` (with capitalized `Http`).

Fixing this would also allow the docs processor to automatically link `HttpResponse` occurrences to the [`HttpResponse` API docs][3].

[1]: https://angular.io/api/common/http/HttpClient
[2]: https://github.com/angular/angular/blob/master/packages/common/http/src/client.ts#L2538
[3]: https://angular.io/api/common/http/HttpResponse

**Comment by nicholasp** [comment]
Shall I try this? There is also ```HTTPEvents```(11), ```HTTPevents```(5), ```HTTPRequest```(1), ```HTTPresponse```(1)

**Comment by bampakoa** [comment]
hey @nicholasp . Thanks very much for your initiative to work on that issue 😃 

As far as `HttpResponse` is concerned, we are currently organizing a new workshop on Thursday and this issue is among others that participants will be asked to work on. However, feel free to correct all the others that you mention. I think it would be great for the Angular documentation if you could do 👌

**Comment by nicholasp** [comment]
sorry for the inconvenience! I am in shape from your previous workshop 💪😂

**Comment by tzimpoulog** [comment]
Picking up this issue

**Comment by bampakoa** [comment]
Related PR: https://github.com/angular/angular/pull/39860
